### ISSUE TITLE
placement --check crashes from time to time

### ISSUE THREAD

**Issue by calmip** [calmip/placement#11]
Sometimes` placement --check=ALL` crashes with the following messages:

```
placement --check=ALL
Traceback (most recent call last):
  File "/home/ecourcelle/placement/lib/placement.py", line 460, in <module>
    main()
  File "/home/ecourcelle/placement/lib/placement.py", line 179, in main
    print (o)
  File "/home/ecourcelle/placement/lib/printing.py", line 335, in __str__
    rvl += self.__getCpuBinding(self._tasks_binding)
  File "/home/ecourcelle/placement/lib/printing.py", line 443, in __getCpuBinding
    rvl += "\n" + m.getGpuInfo(self._tasks_binding)
  File "/home/ecourcelle/placement/lib/matrix.py", line 165, in getGpuInfo
    rvl += 'POWER           ' + col_skipped + getGauge(g['P'],self.__hard.CORES_PER_SOCKET) + ' ' + str(g['P']) + "%\n"
  File "/home/ecourcelle/placement/lib/utilities.py", line 281, in getGauge
    raise ValueError( "INTERNAL ERROR - " + str(value) +" should be in the interval [0-100]")
ValueError: INTERNAL ERROR - 102 should be in the interval [0-100]

```

**Comment by calmip** [comment]
Fix in 1.11.1
